version: '3.8'

volumes:
  postgres_data:
  test_postgres_data:

services:
  postgres-service:
    container_name: postgres-service
    image: postgres:13.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
      - POSTGRES_DB=main

  app-service:
    container_name: app-service
    build: .
    volumes:
      - .:/usr/src/app/
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 80
    ports:
      - '4096:80'
    environment:
      - DATABASE_URL=postgresql+asyncpg://main:main@postgres-service:5432/main
    depends_on:
      - postgres-service