"""None

Revision ID: 4edbc35b7062
Revises: 21d1a8400440
Create Date: 2022-01-04 07:00:52.533473

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4edbc35b7062'
down_revision = '21d1a8400440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
